const dataProduct = [
    {
      id: 1,
      name: "Syltherine",
      description: "Stylish cafe chair",
      image: "asset/images/product/product-1.jpg",
      price: 2500000,
      discount: 40,
      isDiscount: true,
      isNew: false,
      isOld: false,
      startingprice: 3500000,
    },
    {
      id: 2,
      name: "Leviosa",
      description: "Stylish cafe chair",
      image: "asset/images/product/product-2.jpg",
      price: 2500000,
      isDiscount: false,
      isNew: true,
      isOld: false,
      startingprice: '',
    },
    {
      id: 3,
      name: "Lolito",
      description: "Luxury bi sofa",
      image: "asset/images/product/product-3.jpg",
      price: 7000000,
      discount: 30,
      isDiscount: true,
      isNew: false,
      isOld: false,
      startingprice: 14000000,
    },
    {
      id: 4,
      name: "Respira",
      description: "Outdoor bar table and stool",
      image: "asset/images/product/product-4.jpg",
      price: 500000,
      isDiscount: false,
      isNew: false,
      isOld: false,
      startingprice: 0,
    },
    {
        id: 5,
        name: "Sofa Minimalist",
        description: "Minimalist flower pot",
        image: "asset/images/product/product-21.png",
        price: 900000,
        label: 20,
        startingprice: 120000,
      },
      {
        id: 6,
        name: "Syltherine",
        description: "Stylish cafe chair",
        image: "asset/images/product/product-1.jpg",
        price: 2500000,
        label: 30,
        startingprice: 3500000,
      },
  ];
  
  export default dataProduct;
  