const dbProduct = [
  {
    id: 1,
    name: "Syltherine",
    description: "Stylish cafe chair",
    image: "asset/images/product/product-1.jpg",
    price: 2500000,
    label: 30,
    startingprice: 3500000,
  },
  {
    id: 2,
    name: "Leviosa",
    description: "Stylish cafe chair",
    image: "asset/images/product/product-2.jpg",
    price: 2500000,
    label: "",
    startingprice: 0,
  },
  {
    id: 3,
    name: "Lolito",
    description: "Luxury bi sofa",
    image: "asset/images/product/product-3.jpg",
    price: 7000000,
    label: 50,
    startingprice: 14000000,
  },
  {
    id: 4,
    name: "Respira",
    description: "Outdoor bar table and stool",
    image: "asset/images/product/product-4.jpg",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 5,
    name: "Grifo",
    description: "Night Lamp",
    image: "asset/images/product/product-5.jpg",
    price: 1500000,
    label: "",
    startingprice: 0,
  },
  {
    id: 6,
    name: "Muggo",
    description: "Small mug",
    image: "asset/images/product/product-6.jpg",
    price: 150000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 7,
    name: "Pingky",
    description: "Cute bed set",
    image: "asset/images/product/product-7.jpg",
    price: 7000000,
    label: 50,
    startingprice: 14000000,
  },
  {
    id: 8,
    name: "Potty",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-8.jpg",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 9,
    name: "Potty",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-9.png",
    price: 900000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 10,
    name: "Potty",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-10.png",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 11,
    name: "Figure Minimalist",
    description: "Minimalist flower | pot",
    image: "asset/images/product/product-11.png",
    price: 500000,
    label: 30,
    startingprice: 0,
  },
  {
    id: 12,
    name: "Full Set Table Minimalis",
    description: "Table Minimalist",
    image: "asset/images/product/product-12.jpg",
    price: 800000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 13,
    name: "Potty",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-13.jpg",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 14,
    name: "product 14",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-14.jpg",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 15,
    name: "Potty",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-15.jpg",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 16,
    name: "Potty",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-16.png",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 17,
    name: "Sofa Minimalist",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-17.png",
    price: 800000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 18,
    name: "Sofa Minimalist",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-18.png",
    price: 900000,
    label: 20,
    startingprice: 120000,
  },
  {
    id: 19,
    name: "Sofa Minimalist",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-19.png",
    price: 900000,
    label: 20,
    startingprice: 120000,
  },
  {
    id: 20,
    name: "Sofa Minimalist",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-20.png",
    price: 900000,
    label: 20,
    startingprice: 120000,
  },
  {
    id: 21,
    name: "Sofa Minimalist",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-21.png",
    price: 900000,
    label: 20,
    startingprice: 120000,
  },
  {
    id: 22,
    name: "Syltherine",
    description: "Stylish cafe chair",
    image: "asset/images/product/product-1.jpg",
    price: 2500000,
    label: 30,
    startingprice: 3500000,
  },
  {
    id: 23,
    name: "Leviosa",
    description: "Stylish cafe chair",
    image: "asset/images/product/product-2.jpg",
    price: 2500000,
    label: "",
    startingprice: 0,
  },
  {
    id: 24,
    name: "Lolito",
    description: "Luxury bi sofa",
    image: "asset/images/product/product-3.jpg",
    price: 7000000,
    label: 50,
    startingprice: 14000000,
  },
  {
    id: 25,
    name: "Respira",
    description: "Outdoor bar table and stool",
    image: "asset/images/product/product-4.jpg",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 26,
    name: "Grifo",
    description: "Night Lamp",
    image: "asset/images/product/product-5.jpg",
    price: 1500000,
    label: "",
    startingprice: 0,
  },
  {
    id: 27,
    name: "Muggo",
    description: "Small mug",
    image: "asset/images/product/product-6.jpg",
    price: 150000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 28,
    name: "Syltherine",
    description: "Stylish cafe chair",
    image: "asset/images/product/product-1.jpg",
    price: 2500000,
    label: 30,
    startingprice: 3500000,
  },
  {
    id: 29,
    name: "Leviosa",
    description: "Stylish cafe chair",
    image: "asset/images/product/product-2.jpg",
    price: 2500000,
    label: "",
    startingprice: 0,
  },
  {
    id: 30,
    name: "Lolito",
    description: "Luxury bi sofa",
    image: "asset/images/product/product-3.jpg",
    price: 7000000,
    label: 50,
    startingprice: 14000000,
  },
  {
    id: 31,
    name: "Respira",
    description: "Outdoor bar table and stool",
    image: "asset/images/product/product-4.jpg",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 32,
    name: "Grifo",
    description: "Night Lamp",
    image: "asset/images/product/product-5.jpg",
    price: 1500000,
    label: "",
    startingprice: 0,
  },
  {
    id: 33,
    name: "product 14",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-14.jpg",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 34,
    name: "Potty",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-15.jpg",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 35,
    name: "Potty",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-16.png",
    price: 500000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 36,
    name: "Sofa Minimalist",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-17.png",
    price: 800000,
    label: "New",
    startingprice: 0,
  },
  {
    id: 37,
    name: "Sofa Minimalist",
    description: "Minimalist flower pot",
    image: "asset/images/product/product-17.png",
    price: 800000,
    label: "New",
    startingprice: 0,
  },
];

export default dbProduct;
